// Copyright (c) 2016 Uber Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/m3db/m3cluster/services/types.go

package services

import (
	gomock "github.com/golang/mock/gomock"
	shard "github.com/m3db/m3cluster/shard"
	watch "github.com/m3db/m3x/watch"
)

// Mock of Services interface
type MockServices struct {
	ctrl     *gomock.Controller
	recorder *_MockServicesRecorder
}

// Recorder for MockServices (not exported)
type _MockServicesRecorder struct {
	mock *MockServices
}

func NewMockServices(ctrl *gomock.Controller) *MockServices {
	mock := &MockServices{ctrl: ctrl}
	mock.recorder = &_MockServicesRecorder{mock}
	return mock
}

func (_m *MockServices) EXPECT() *_MockServicesRecorder {
	return _m.recorder
}

func (_m *MockServices) Advertise(ad Advertisement) error {
	ret := _m.ctrl.Call(_m, "Advertise", ad)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockServicesRecorder) Advertise(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Advertise", arg0)
}

func (_m *MockServices) Unadvertise(service ServiceQuery, id string) error {
	ret := _m.ctrl.Call(_m, "Unadvertise", service, id)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockServicesRecorder) Unadvertise(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Unadvertise", arg0, arg1)
}

func (_m *MockServices) Query(service ServiceQuery, opts QueryOptions) (Service, error) {
	ret := _m.ctrl.Call(_m, "Query", service, opts)
	ret0, _ := ret[0].(Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockServicesRecorder) Query(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Query", arg0, arg1)
}

func (_m *MockServices) Watch(service ServiceQuery, opts QueryOptions) (watch.Watch, error) {
	ret := _m.ctrl.Call(_m, "Watch", service, opts)
	ret0, _ := ret[0].(watch.Watch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockServicesRecorder) Watch(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Watch", arg0, arg1)
}

func (_m *MockServices) PlacementService(service ServiceQuery) (PlacementService, error) {
	ret := _m.ctrl.Call(_m, "PlacementService", service)
	ret0, _ := ret[0].(PlacementService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockServicesRecorder) PlacementService(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "PlacementService", arg0)
}

func (_m *MockServices) MetadataService(service ServiceQuery) (MetadataService, error) {
	ret := _m.ctrl.Call(_m, "MetadataService", service)
	ret0, _ := ret[0].(MetadataService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockServicesRecorder) MetadataService(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "MetadataService", arg0)
}

// Mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *_MockServiceRecorder
}

// Recorder for MockService (not exported)
type _MockServiceRecorder struct {
	mock *MockService
}

func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &_MockServiceRecorder{mock}
	return mock
}

func (_m *MockService) EXPECT() *_MockServiceRecorder {
	return _m.recorder
}

func (_m *MockService) Instance(instanceID string) (ServiceInstance, error) {
	ret := _m.ctrl.Call(_m, "Instance", instanceID)
	ret0, _ := ret[0].(ServiceInstance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockServiceRecorder) Instance(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Instance", arg0)
}

func (_m *MockService) Instances() []ServiceInstance {
	ret := _m.ctrl.Call(_m, "Instances")
	ret0, _ := ret[0].([]ServiceInstance)
	return ret0
}

func (_mr *_MockServiceRecorder) Instances() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Instances")
}

func (_m *MockService) SetInstances(insts []ServiceInstance) Service {
	ret := _m.ctrl.Call(_m, "SetInstances", insts)
	ret0, _ := ret[0].(Service)
	return ret0
}

func (_mr *_MockServiceRecorder) SetInstances(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetInstances", arg0)
}

func (_m *MockService) Replication() ServiceReplication {
	ret := _m.ctrl.Call(_m, "Replication")
	ret0, _ := ret[0].(ServiceReplication)
	return ret0
}

func (_mr *_MockServiceRecorder) Replication() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Replication")
}

func (_m *MockService) SetReplication(r ServiceReplication) Service {
	ret := _m.ctrl.Call(_m, "SetReplication", r)
	ret0, _ := ret[0].(Service)
	return ret0
}

func (_mr *_MockServiceRecorder) SetReplication(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetReplication", arg0)
}

func (_m *MockService) Sharding() ServiceSharding {
	ret := _m.ctrl.Call(_m, "Sharding")
	ret0, _ := ret[0].(ServiceSharding)
	return ret0
}

func (_mr *_MockServiceRecorder) Sharding() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Sharding")
}

func (_m *MockService) SetSharding(s ServiceSharding) Service {
	ret := _m.ctrl.Call(_m, "SetSharding", s)
	ret0, _ := ret[0].(Service)
	return ret0
}

func (_mr *_MockServiceRecorder) SetSharding(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetSharding", arg0)
}

// Mock of ServiceReplication interface
type MockServiceReplication struct {
	ctrl     *gomock.Controller
	recorder *_MockServiceReplicationRecorder
}

// Recorder for MockServiceReplication (not exported)
type _MockServiceReplicationRecorder struct {
	mock *MockServiceReplication
}

func NewMockServiceReplication(ctrl *gomock.Controller) *MockServiceReplication {
	mock := &MockServiceReplication{ctrl: ctrl}
	mock.recorder = &_MockServiceReplicationRecorder{mock}
	return mock
}

func (_m *MockServiceReplication) EXPECT() *_MockServiceReplicationRecorder {
	return _m.recorder
}

func (_m *MockServiceReplication) Replicas() int {
	ret := _m.ctrl.Call(_m, "Replicas")
	ret0, _ := ret[0].(int)
	return ret0
}

func (_mr *_MockServiceReplicationRecorder) Replicas() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Replicas")
}

func (_m *MockServiceReplication) SetReplicas(r int) ServiceReplication {
	ret := _m.ctrl.Call(_m, "SetReplicas", r)
	ret0, _ := ret[0].(ServiceReplication)
	return ret0
}

func (_mr *_MockServiceReplicationRecorder) SetReplicas(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetReplicas", arg0)
}

// Mock of ServiceSharding interface
type MockServiceSharding struct {
	ctrl     *gomock.Controller
	recorder *_MockServiceShardingRecorder
}

// Recorder for MockServiceSharding (not exported)
type _MockServiceShardingRecorder struct {
	mock *MockServiceSharding
}

func NewMockServiceSharding(ctrl *gomock.Controller) *MockServiceSharding {
	mock := &MockServiceSharding{ctrl: ctrl}
	mock.recorder = &_MockServiceShardingRecorder{mock}
	return mock
}

func (_m *MockServiceSharding) EXPECT() *_MockServiceShardingRecorder {
	return _m.recorder
}

func (_m *MockServiceSharding) NumShards() int {
	ret := _m.ctrl.Call(_m, "NumShards")
	ret0, _ := ret[0].(int)
	return ret0
}

func (_mr *_MockServiceShardingRecorder) NumShards() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "NumShards")
}

func (_m *MockServiceSharding) SetNumShards(n int) ServiceSharding {
	ret := _m.ctrl.Call(_m, "SetNumShards", n)
	ret0, _ := ret[0].(ServiceSharding)
	return ret0
}

func (_mr *_MockServiceShardingRecorder) SetNumShards(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetNumShards", arg0)
}

// Mock of ServiceInstance interface
type MockServiceInstance struct {
	ctrl     *gomock.Controller
	recorder *_MockServiceInstanceRecorder
}

// Recorder for MockServiceInstance (not exported)
type _MockServiceInstanceRecorder struct {
	mock *MockServiceInstance
}

func NewMockServiceInstance(ctrl *gomock.Controller) *MockServiceInstance {
	mock := &MockServiceInstance{ctrl: ctrl}
	mock.recorder = &_MockServiceInstanceRecorder{mock}
	return mock
}

func (_m *MockServiceInstance) EXPECT() *_MockServiceInstanceRecorder {
	return _m.recorder
}

func (_m *MockServiceInstance) Service() string {
	ret := _m.ctrl.Call(_m, "Service")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockServiceInstanceRecorder) Service() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Service")
}

func (_m *MockServiceInstance) SetService(s string) ServiceInstance {
	ret := _m.ctrl.Call(_m, "SetService", s)
	ret0, _ := ret[0].(ServiceInstance)
	return ret0
}

func (_mr *_MockServiceInstanceRecorder) SetService(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetService", arg0)
}

func (_m *MockServiceInstance) ID() string {
	ret := _m.ctrl.Call(_m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockServiceInstanceRecorder) ID() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ID")
}

func (_m *MockServiceInstance) SetID(id string) ServiceInstance {
	ret := _m.ctrl.Call(_m, "SetID", id)
	ret0, _ := ret[0].(ServiceInstance)
	return ret0
}

func (_mr *_MockServiceInstanceRecorder) SetID(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetID", arg0)
}

func (_m *MockServiceInstance) Zone() string {
	ret := _m.ctrl.Call(_m, "Zone")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockServiceInstanceRecorder) Zone() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Zone")
}

func (_m *MockServiceInstance) SetZone(z string) ServiceInstance {
	ret := _m.ctrl.Call(_m, "SetZone", z)
	ret0, _ := ret[0].(ServiceInstance)
	return ret0
}

func (_mr *_MockServiceInstanceRecorder) SetZone(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetZone", arg0)
}

func (_m *MockServiceInstance) Endpoint() string {
	ret := _m.ctrl.Call(_m, "Endpoint")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockServiceInstanceRecorder) Endpoint() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Endpoint")
}

func (_m *MockServiceInstance) SetEndpoint(e string) ServiceInstance {
	ret := _m.ctrl.Call(_m, "SetEndpoint", e)
	ret0, _ := ret[0].(ServiceInstance)
	return ret0
}

func (_mr *_MockServiceInstanceRecorder) SetEndpoint(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetEndpoint", arg0)
}

func (_m *MockServiceInstance) Shards() shard.Shards {
	ret := _m.ctrl.Call(_m, "Shards")
	ret0, _ := ret[0].(shard.Shards)
	return ret0
}

func (_mr *_MockServiceInstanceRecorder) Shards() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Shards")
}

func (_m *MockServiceInstance) SetShards(s shard.Shards) ServiceInstance {
	ret := _m.ctrl.Call(_m, "SetShards", s)
	ret0, _ := ret[0].(ServiceInstance)
	return ret0
}

func (_mr *_MockServiceInstanceRecorder) SetShards(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetShards", arg0)
}

// Mock of Advertisement interface
type MockAdvertisement struct {
	ctrl     *gomock.Controller
	recorder *_MockAdvertisementRecorder
}

// Recorder for MockAdvertisement (not exported)
type _MockAdvertisementRecorder struct {
	mock *MockAdvertisement
}

func NewMockAdvertisement(ctrl *gomock.Controller) *MockAdvertisement {
	mock := &MockAdvertisement{ctrl: ctrl}
	mock.recorder = &_MockAdvertisementRecorder{mock}
	return mock
}

func (_m *MockAdvertisement) EXPECT() *_MockAdvertisementRecorder {
	return _m.recorder
}

func (_m *MockAdvertisement) ID() string {
	ret := _m.ctrl.Call(_m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockAdvertisementRecorder) ID() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ID")
}

func (_m *MockAdvertisement) SetID(id string) Advertisement {
	ret := _m.ctrl.Call(_m, "SetID", id)
	ret0, _ := ret[0].(Advertisement)
	return ret0
}

func (_mr *_MockAdvertisementRecorder) SetID(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetID", arg0)
}

func (_m *MockAdvertisement) Service() ServiceQuery {
	ret := _m.ctrl.Call(_m, "Service")
	ret0, _ := ret[0].(ServiceQuery)
	return ret0
}

func (_mr *_MockAdvertisementRecorder) Service() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Service")
}

func (_m *MockAdvertisement) SetService(service ServiceQuery) Advertisement {
	ret := _m.ctrl.Call(_m, "SetService", service)
	ret0, _ := ret[0].(Advertisement)
	return ret0
}

func (_mr *_MockAdvertisementRecorder) SetService(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetService", arg0)
}

func (_m *MockAdvertisement) Health() func() error {
	ret := _m.ctrl.Call(_m, "Health")
	ret0, _ := ret[0].(func() error)
	return ret0
}

func (_mr *_MockAdvertisementRecorder) Health() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Health")
}

func (_m *MockAdvertisement) SetHealth(health func() error) Advertisement {
	ret := _m.ctrl.Call(_m, "SetHealth", health)
	ret0, _ := ret[0].(Advertisement)
	return ret0
}

func (_mr *_MockAdvertisementRecorder) SetHealth(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetHealth", arg0)
}

func (_m *MockAdvertisement) Endpoint() string {
	ret := _m.ctrl.Call(_m, "Endpoint")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockAdvertisementRecorder) Endpoint() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Endpoint")
}

func (_m *MockAdvertisement) SetEndpoint(e string) Advertisement {
	ret := _m.ctrl.Call(_m, "SetEndpoint", e)
	ret0, _ := ret[0].(Advertisement)
	return ret0
}

func (_mr *_MockAdvertisementRecorder) SetEndpoint(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetEndpoint", arg0)
}

// Mock of ServiceQuery interface
type MockServiceQuery struct {
	ctrl     *gomock.Controller
	recorder *_MockServiceQueryRecorder
}

// Recorder for MockServiceQuery (not exported)
type _MockServiceQueryRecorder struct {
	mock *MockServiceQuery
}

func NewMockServiceQuery(ctrl *gomock.Controller) *MockServiceQuery {
	mock := &MockServiceQuery{ctrl: ctrl}
	mock.recorder = &_MockServiceQueryRecorder{mock}
	return mock
}

func (_m *MockServiceQuery) EXPECT() *_MockServiceQueryRecorder {
	return _m.recorder
}

func (_m *MockServiceQuery) Service() string {
	ret := _m.ctrl.Call(_m, "Service")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockServiceQueryRecorder) Service() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Service")
}

func (_m *MockServiceQuery) SetService(s string) ServiceQuery {
	ret := _m.ctrl.Call(_m, "SetService", s)
	ret0, _ := ret[0].(ServiceQuery)
	return ret0
}

func (_mr *_MockServiceQueryRecorder) SetService(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetService", arg0)
}

func (_m *MockServiceQuery) Environment() string {
	ret := _m.ctrl.Call(_m, "Environment")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockServiceQueryRecorder) Environment() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Environment")
}

func (_m *MockServiceQuery) SetEnvironment(env string) ServiceQuery {
	ret := _m.ctrl.Call(_m, "SetEnvironment", env)
	ret0, _ := ret[0].(ServiceQuery)
	return ret0
}

func (_mr *_MockServiceQueryRecorder) SetEnvironment(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetEnvironment", arg0)
}

func (_m *MockServiceQuery) Zone() string {
	ret := _m.ctrl.Call(_m, "Zone")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockServiceQueryRecorder) Zone() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Zone")
}

func (_m *MockServiceQuery) SetZone(zone string) ServiceQuery {
	ret := _m.ctrl.Call(_m, "SetZone", zone)
	ret0, _ := ret[0].(ServiceQuery)
	return ret0
}

func (_mr *_MockServiceQueryRecorder) SetZone(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetZone", arg0)
}

// Mock of QueryOptions interface
type MockQueryOptions struct {
	ctrl     *gomock.Controller
	recorder *_MockQueryOptionsRecorder
}

// Recorder for MockQueryOptions (not exported)
type _MockQueryOptionsRecorder struct {
	mock *MockQueryOptions
}

func NewMockQueryOptions(ctrl *gomock.Controller) *MockQueryOptions {
	mock := &MockQueryOptions{ctrl: ctrl}
	mock.recorder = &_MockQueryOptionsRecorder{mock}
	return mock
}

func (_m *MockQueryOptions) EXPECT() *_MockQueryOptionsRecorder {
	return _m.recorder
}

func (_m *MockQueryOptions) IncludeUnhealthy() bool {
	ret := _m.ctrl.Call(_m, "IncludeUnhealthy")
	ret0, _ := ret[0].(bool)
	return ret0
}

func (_mr *_MockQueryOptionsRecorder) IncludeUnhealthy() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "IncludeUnhealthy")
}

func (_m *MockQueryOptions) SetIncludeUnhealthy(h bool) QueryOptions {
	ret := _m.ctrl.Call(_m, "SetIncludeUnhealthy", h)
	ret0, _ := ret[0].(QueryOptions)
	return ret0
}

func (_mr *_MockQueryOptionsRecorder) SetIncludeUnhealthy(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetIncludeUnhealthy", arg0)
}

// Mock of ServiceMetadata interface
type MockServiceMetadata struct {
	ctrl     *gomock.Controller
	recorder *_MockServiceMetadataRecorder
}

// Recorder for MockServiceMetadata (not exported)
type _MockServiceMetadataRecorder struct {
	mock *MockServiceMetadata
}

func NewMockServiceMetadata(ctrl *gomock.Controller) *MockServiceMetadata {
	mock := &MockServiceMetadata{ctrl: ctrl}
	mock.recorder = &_MockServiceMetadataRecorder{mock}
	return mock
}

func (_m *MockServiceMetadata) EXPECT() *_MockServiceMetadataRecorder {
	return _m.recorder
}

func (_m *MockServiceMetadata) Ports() []uint64 {
	ret := _m.ctrl.Call(_m, "Ports")
	ret0, _ := ret[0].([]uint64)
	return ret0
}

func (_mr *_MockServiceMetadataRecorder) Ports() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Ports")
}

func (_m *MockServiceMetadata) LivenessInterval() uint64 {
	ret := _m.ctrl.Call(_m, "LivenessInterval")
	ret0, _ := ret[0].(uint64)
	return ret0
}

func (_mr *_MockServiceMetadataRecorder) LivenessInterval() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "LivenessInterval")
}

func (_m *MockServiceMetadata) HeartbeatInterval() uint64 {
	ret := _m.ctrl.Call(_m, "HeartbeatInterval")
	ret0, _ := ret[0].(uint64)
	return ret0
}

func (_mr *_MockServiceMetadataRecorder) HeartbeatInterval() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "HeartbeatInterval")
}

// Mock of MetadataService interface
type MockMetadataService struct {
	ctrl     *gomock.Controller
	recorder *_MockMetadataServiceRecorder
}

// Recorder for MockMetadataService (not exported)
type _MockMetadataServiceRecorder struct {
	mock *MockMetadataService
}

func NewMockMetadataService(ctrl *gomock.Controller) *MockMetadataService {
	mock := &MockMetadataService{ctrl: ctrl}
	mock.recorder = &_MockMetadataServiceRecorder{mock}
	return mock
}

func (_m *MockMetadataService) EXPECT() *_MockMetadataServiceRecorder {
	return _m.recorder
}

func (_m *MockMetadataService) Metadata() (ServiceMetadata, error) {
	ret := _m.ctrl.Call(_m, "Metadata")
	ret0, _ := ret[0].(ServiceMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockMetadataServiceRecorder) Metadata() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Metadata")
}

func (_m *MockMetadataService) SetMetadata(m ServiceMetadata) error {
	ret := _m.ctrl.Call(_m, "SetMetadata", m)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockMetadataServiceRecorder) SetMetadata(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetMetadata", arg0)
}

// Mock of PlacementService interface
type MockPlacementService struct {
	ctrl     *gomock.Controller
	recorder *_MockPlacementServiceRecorder
}

// Recorder for MockPlacementService (not exported)
type _MockPlacementServiceRecorder struct {
	mock *MockPlacementService
}

func NewMockPlacementService(ctrl *gomock.Controller) *MockPlacementService {
	mock := &MockPlacementService{ctrl: ctrl}
	mock.recorder = &_MockPlacementServiceRecorder{mock}
	return mock
}

func (_m *MockPlacementService) EXPECT() *_MockPlacementServiceRecorder {
	return _m.recorder
}

func (_m *MockPlacementService) BuildInitialPlacement(hosts []PlacementInstance, numShards int, rf int) (ServicePlacement, error) {
	ret := _m.ctrl.Call(_m, "BuildInitialPlacement", hosts, numShards, rf)
	ret0, _ := ret[0].(ServicePlacement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockPlacementServiceRecorder) BuildInitialPlacement(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "BuildInitialPlacement", arg0, arg1, arg2)
}

func (_m *MockPlacementService) AddReplica() (ServicePlacement, error) {
	ret := _m.ctrl.Call(_m, "AddReplica")
	ret0, _ := ret[0].(ServicePlacement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockPlacementServiceRecorder) AddReplica() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AddReplica")
}

func (_m *MockPlacementService) AddInstance(candidates []PlacementInstance) (ServicePlacement, error) {
	ret := _m.ctrl.Call(_m, "AddInstance", candidates)
	ret0, _ := ret[0].(ServicePlacement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockPlacementServiceRecorder) AddInstance(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AddInstance", arg0)
}

func (_m *MockPlacementService) RemoveInstance(i PlacementInstance) (ServicePlacement, error) {
	ret := _m.ctrl.Call(_m, "RemoveInstance", i)
	ret0, _ := ret[0].(ServicePlacement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockPlacementServiceRecorder) RemoveInstance(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "RemoveInstance", arg0)
}

func (_m *MockPlacementService) ReplaceInstance(leavingInstance PlacementInstance, candidates []PlacementInstance) (ServicePlacement, error) {
	ret := _m.ctrl.Call(_m, "ReplaceInstance", leavingInstance, candidates)
	ret0, _ := ret[0].(ServicePlacement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockPlacementServiceRecorder) ReplaceInstance(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ReplaceInstance", arg0, arg1)
}

func (_m *MockPlacementService) Placement() (ServicePlacement, error) {
	ret := _m.ctrl.Call(_m, "Placement")
	ret0, _ := ret[0].(ServicePlacement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockPlacementServiceRecorder) Placement() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Placement")
}

// Mock of ServicePlacement interface
type MockServicePlacement struct {
	ctrl     *gomock.Controller
	recorder *_MockServicePlacementRecorder
}

// Recorder for MockServicePlacement (not exported)
type _MockServicePlacementRecorder struct {
	mock *MockServicePlacement
}

func NewMockServicePlacement(ctrl *gomock.Controller) *MockServicePlacement {
	mock := &MockServicePlacement{ctrl: ctrl}
	mock.recorder = &_MockServicePlacementRecorder{mock}
	return mock
}

func (_m *MockServicePlacement) EXPECT() *_MockServicePlacementRecorder {
	return _m.recorder
}

func (_m *MockServicePlacement) Instances() []PlacementInstance {
	ret := _m.ctrl.Call(_m, "Instances")
	ret0, _ := ret[0].([]PlacementInstance)
	return ret0
}

func (_mr *_MockServicePlacementRecorder) Instances() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Instances")
}

func (_m *MockServicePlacement) NumInstances() int {
	ret := _m.ctrl.Call(_m, "NumInstances")
	ret0, _ := ret[0].(int)
	return ret0
}

func (_mr *_MockServicePlacementRecorder) NumInstances() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "NumInstances")
}

func (_m *MockServicePlacement) Instance(id string) PlacementInstance {
	ret := _m.ctrl.Call(_m, "Instance", id)
	ret0, _ := ret[0].(PlacementInstance)
	return ret0
}

func (_mr *_MockServicePlacementRecorder) Instance(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Instance", arg0)
}

func (_m *MockServicePlacement) ReplicaFactor() int {
	ret := _m.ctrl.Call(_m, "ReplicaFactor")
	ret0, _ := ret[0].(int)
	return ret0
}

func (_mr *_MockServicePlacementRecorder) ReplicaFactor() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ReplicaFactor")
}

func (_m *MockServicePlacement) Shards() []uint32 {
	ret := _m.ctrl.Call(_m, "Shards")
	ret0, _ := ret[0].([]uint32)
	return ret0
}

func (_mr *_MockServicePlacementRecorder) Shards() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Shards")
}

func (_m *MockServicePlacement) NumShards() int {
	ret := _m.ctrl.Call(_m, "NumShards")
	ret0, _ := ret[0].(int)
	return ret0
}

func (_mr *_MockServicePlacementRecorder) NumShards() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "NumShards")
}

func (_m *MockServicePlacement) Validate() error {
	ret := _m.ctrl.Call(_m, "Validate")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockServicePlacementRecorder) Validate() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Validate")
}

func (_m *MockServicePlacement) Copy() ServicePlacement {
	ret := _m.ctrl.Call(_m, "Copy")
	ret0, _ := ret[0].(ServicePlacement)
	return ret0
}

func (_mr *_MockServicePlacementRecorder) Copy() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Copy")
}

// Mock of PlacementInstance interface
type MockPlacementInstance struct {
	ctrl     *gomock.Controller
	recorder *_MockPlacementInstanceRecorder
}

// Recorder for MockPlacementInstance (not exported)
type _MockPlacementInstanceRecorder struct {
	mock *MockPlacementInstance
}

func NewMockPlacementInstance(ctrl *gomock.Controller) *MockPlacementInstance {
	mock := &MockPlacementInstance{ctrl: ctrl}
	mock.recorder = &_MockPlacementInstanceRecorder{mock}
	return mock
}

func (_m *MockPlacementInstance) EXPECT() *_MockPlacementInstanceRecorder {
	return _m.recorder
}

func (_m *MockPlacementInstance) String() string {
	ret := _m.ctrl.Call(_m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockPlacementInstanceRecorder) String() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "String")
}

func (_m *MockPlacementInstance) ID() string {
	ret := _m.ctrl.Call(_m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockPlacementInstanceRecorder) ID() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ID")
}

func (_m *MockPlacementInstance) SetID(id string) PlacementInstance {
	ret := _m.ctrl.Call(_m, "SetID", id)
	ret0, _ := ret[0].(PlacementInstance)
	return ret0
}

func (_mr *_MockPlacementInstanceRecorder) SetID(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetID", arg0)
}

func (_m *MockPlacementInstance) Rack() string {
	ret := _m.ctrl.Call(_m, "Rack")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockPlacementInstanceRecorder) Rack() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Rack")
}

func (_m *MockPlacementInstance) SetRack(r string) PlacementInstance {
	ret := _m.ctrl.Call(_m, "SetRack", r)
	ret0, _ := ret[0].(PlacementInstance)
	return ret0
}

func (_mr *_MockPlacementInstanceRecorder) SetRack(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetRack", arg0)
}

func (_m *MockPlacementInstance) Zone() string {
	ret := _m.ctrl.Call(_m, "Zone")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockPlacementInstanceRecorder) Zone() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Zone")
}

func (_m *MockPlacementInstance) SetZone(z string) PlacementInstance {
	ret := _m.ctrl.Call(_m, "SetZone", z)
	ret0, _ := ret[0].(PlacementInstance)
	return ret0
}

func (_mr *_MockPlacementInstanceRecorder) SetZone(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetZone", arg0)
}

func (_m *MockPlacementInstance) Weight() uint32 {
	ret := _m.ctrl.Call(_m, "Weight")
	ret0, _ := ret[0].(uint32)
	return ret0
}

func (_mr *_MockPlacementInstanceRecorder) Weight() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Weight")
}

func (_m *MockPlacementInstance) SetWeight(w uint32) PlacementInstance {
	ret := _m.ctrl.Call(_m, "SetWeight", w)
	ret0, _ := ret[0].(PlacementInstance)
	return ret0
}

func (_mr *_MockPlacementInstanceRecorder) SetWeight(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetWeight", arg0)
}

func (_m *MockPlacementInstance) Name() string {
	ret := _m.ctrl.Call(_m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockPlacementInstanceRecorder) Name() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Name")
}

func (_m *MockPlacementInstance) SetName(n string) PlacementInstance {
	ret := _m.ctrl.Call(_m, "SetName", n)
	ret0, _ := ret[0].(PlacementInstance)
	return ret0
}

func (_mr *_MockPlacementInstanceRecorder) SetName(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetName", arg0)
}

func (_m *MockPlacementInstance) Port() string {
	ret := _m.ctrl.Call(_m, "Port")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockPlacementInstanceRecorder) Port() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Port")
}

func (_m *MockPlacementInstance) SetPort(p string) PlacementInstance {
	ret := _m.ctrl.Call(_m, "SetPort", p)
	ret0, _ := ret[0].(PlacementInstance)
	return ret0
}

func (_mr *_MockPlacementInstanceRecorder) SetPort(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetPort", arg0)
}

func (_m *MockPlacementInstance) Shards() shard.Shards {
	ret := _m.ctrl.Call(_m, "Shards")
	ret0, _ := ret[0].(shard.Shards)
	return ret0
}

func (_mr *_MockPlacementInstanceRecorder) Shards() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Shards")
}

func (_m *MockPlacementInstance) SetShards(s shard.Shards) PlacementInstance {
	ret := _m.ctrl.Call(_m, "SetShards", s)
	ret0, _ := ret[0].(PlacementInstance)
	return ret0
}

func (_mr *_MockPlacementInstanceRecorder) SetShards(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetShards", arg0)
}
