// Code generated by "stringer -type CampaignState"; DO NOT EDIT

package leader

import "fmt"

const _CampaignState_name = "CampaignFollowerCampaignLeaderCampaignErrorCampaignClosed"

var _CampaignState_index = [...]uint8{0, 16, 30, 43, 57}

func (i CampaignState) String() string {
	if i < 0 || i >= CampaignState(len(_CampaignState_index)-1) {
		return fmt.Sprintf("CampaignState(%d)", i)
	}
	return _CampaignState_name[_CampaignState_index[i]:_CampaignState_index[i+1]]
}
